### ISSUE TITLE
How to change the text convert Json to excel

### ISSUE THREAD

**Issue by robertrutenge** [praveenkumar-outlook/react-json-excel#1]
Hello , 
I have noticed that the button text "convert Json to excel" is hardcoded , is there a way to change this text by passing it as a prop like <JsonToExcel text="Convert to Excel"> ? Thanks and looking forward your feedback .

**Comment by LeuAlmeida** [comment]
I created a pull request doing exactly this. [You can see there,](https://github.com/praveenkumar-outlook/react-json-excel/pull/8).
A fast solution (but not good) is change in the own node_modules/ the default text.
But in this PR I created a prop in the component that can manipulate the button text.

**Comment by praveenkumar-kalidass** [comment]
Hi @robertrutenge 

There is a prop added for customised button text named as "text". Please make use of it.

**Comment by praveenkumar-kalidass** [comment]
Hi @LeuAlmeida Thank you for pull request.
