### ISSUE TITLE
Changing the button text

### ISSUE THREAD

**Issue by buglessir** [praveenkumar-outlook/react-json-excel#11]
@praveenkumar-outlook , It's really helpful and valuable. but is there any trick to change the download button text or style?

**Comment by praveenkumar-kalidass** [comment]
Hi @buglessir , Thank you for using react-json-excel.

To answer your question,
1. To change download button text, there is a prop named "text" provided in v1.1.0.
2. To provide additional styles, there is a prop name "style".

Hope this helps.
