### ISSUE TITLE
csv no is excel

### ISSUE THREAD

**Issue by ElLuigi** [praveenkumar-outlook/react-json-excel#16]
el formato csv no es un formato de excel, se puede abrie con el excel pero es un formato texto, estas muy confundido en lo que presentas, un formato excel valido es por ejemplo xlsx NO csv

**Comment by praveenkumar-kalidass** [comment]
Hi @ElLuigi ,

Thank you for your valuable feedback. The package rename had already been taken into notice.
Now the package is renamed to `react-json-csv`. Kindly use the same.

Thanks in advance.
